dist: trusty
language: node_js
node_js:
- 9.4.0
cache:
  directories:
  - node_modules

before_install:
- npm install -g greenkeeper-lockfile@1

install:
- npm install

before_script: greenkeeper-lockfile-update

script:
- npm run lint
- npm test

after_script: greenkeeper-lockfile-upload

notifications:
  slack:
    rooms:
      secure: eO4RBCdi33OuAt/EqOs5IAycfsazk89P2lbShMyPg1NczIL/q/Qvk+bjaVRxrXiWBgO3jVcCsi79s8naqSSMUt/GWR14grJP6RQUto6xLM2GJJKPH148MSXoSkPh5XnC8W+Kj57L+NRikVltZNjl5tEPYfn+r2TFDrNqBpWyilAANd82wec7h6xCI2cD19JUYr2Kx4kgKNltLKuVbTxmtgRuLbeIN5cjhDFr4Dt8X0g4aqDHIWrjdz8Tw8I0g2JsZdzQU8+rmkyfnt0Fi/ph6AZCpwgN/hE5h7e94UP3gsI9mI2QmD/XdImCwQEVpZyi/tbSYCNej77W1G+it5oDiAB8n1oEGtq2nVNvVu+Cv9cw2hlCJlC2k08NfpVuHZpl/7UdzVgeoRRZS2c1qKJm4K6ijL9tCRNN1bdqsJY0eDPa77QmLpF7S9xSWi9Ud48nlfr7LkDEns7JkYQ7Lrq5dD3RSTkBwaY/qRZj/JnnEabSm9DB4dnXA/Kj2Eh66AZzTiA5alPLVw2kl4XMClUdVLSsS3ItHlcdKVxypB2OlKrU3bKKyGLj1aQzYfH+sCl69eaB+MYFGlJZgDWNmOrOdhJlm4/Tg0qRh+lWywrso/vv8NG27GErkP1WH3lAsjfcXFFFqXhAIXvJGShuSmbqKSR8JC6304zGqDnX3ZqzgXQ=

env:
  global:
    secure: jxBifRxrQOn2y7yEgGHGCIdf6PYn6ECCtjOS1zi04egGXhPEjeXIXrn8N1vbpNYcCgwDn0vVyvfRpO2s2TjGDIbKBDo/AOmnbIamBymPZqvzHS6ET8jv67u34AxfL0rtgtF95UaJOr+PoMvXNhET/rA0ftuX6xMt6dYPP0srjsIhuhaD8MtoY7fbtayFKRxEdbbiHWPMUi/0gXW9t+9vFzGM6xJusk0sT5yJS0esgmVgOo62eJJZPip8ar6ENMktj/tYZQFDq6WXJEyDxYsvBgzVqcxNIW6R9Cm+LoPgnXAI2WFWAS4iFCl0qcPjOXiZIRy3AfPF2nnBfAw0B1Sa75GceM1uU1fVyTmLcqteqVmAb2e+XinlVcQzfwIo3ddzQQziBBF3KY7pjZ2xx4tvekaZY++wv/AnzHGun3HAdJcWMe/MO3oVonIMqDEhXPN8tmuEZX7JBBQ/d9/iuQOcvMBwA+d3d7pIZbJdrGVXYbNX6llONkkQDHNESiivnGa65PG9EaR5OhP/GZuH1QJY36533r3HMgErlVIiglV+DKDNCZ+wbFjpA7Il6rHYcCFjsxr3VvA0ISZSEEeSpfSPZGFpI8NhpHiSh7oFMARGfEF+s7TuZvUJ1AbUwr2rxCrqQ1UPKU65qfXI6j8dBcQ5kTAo0EpgFlECrrYzT/RK4rA=
