export const PRECOMMITMENTS_BULK_ADD = 'PRECOMMITMENTS_BULK_ADD'
export const PRECOMMITMENTS_BULK_ADD_FAIL = 'PRECOMMITMENTS_BULK_ADD_FAIL'
export const PRECOMMITMENTS_BULK_ADD_SUCCESS = 'PRECOMMITMENTS_BULK_ADD_SUCCESS'
export const PRECOMMITMENT_SINGLE_ADD = 'PRECOMMITMENT_SINGLE_ADD'
export const PRECOMMITMENT_SINGLE_ADD_FAIL = 'PRECOMMITMENT_SINGLE_ADD_FAIL'
export const PRECOMMITMENT_SINGLE_ADD_SUCCESS =
  'PRECOMMITMENT_SINGLE_ADD_SUCCESS'
